Getting rid of the mount point for building of python algorithms

diff --git a/python/bin/build b/python/bin/build
--- a/python/bin/build
+++ b/python/bin/build
@@ -11,6 +11,16 @@ else
     exit 1
 fi
 
+if [ -e "/home/algo/.local" ]; then
+    echo "Making the link will fail"
+    exit 1
+fi
+
+if [ ! -d "dependencies" ]; then
+    mkdir dependencies
+fi
+
+ln -s `pwd`/dependencies /home/algo/.local
 $PIP install -r requirements.txt --user
 
 zip -r algorithm.zip .
diff --git a/python/examples/hello/bin/pipe b/python/examples/hello/bin/pipe
--- a/python/examples/hello/bin/pipe
+++ b/python/examples/hello/bin/pipe
@@ -11,6 +11,10 @@ else
     exit 1
 fi
 
+if [ -e "/home/algo/.local" ]; then
+    echo "Making the link will fail"
+    exit 1
+fi
 
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
